ynput/ayon-python-api

ayon_api/__init__.py, ayon_api/exceptions.py, ayon_api/server_api.py
Added Service helper class with context about running service which is launched from server. Service just have to call 'init_service' on start of process.
This has no effect on server connection api it just helps to receive information from environments and create connection. Logic was copied from `ayclient` (premature server api for services).
=> Service: Initialize helper

ayon_api/__init__.py, ayon_api/utils.py, pyproject.toml
Names of entities in database are strict and limited to spefic characters. Added new function `slugify_string` which converts unicode strings to ascii and replace special characters with unified separator.
Added new dependency `unidecode` which is used to convert unicode string to ascii ([Documentation](https://pypi.org/project/Unidecode/)). The dependency handles non-ascii characters (e.g. `ř` -> `r`). The `slugify_string` function then replace secial characters like `;"'|,./` etc. with separator (can be defined in arguments of function).
=> General: Slugify string helper

ayon_api/server.py, ayon_api/version.py, pyproject.toml
Generator functions returned empty list which is invalid which in Py3 it silently continue but in Py2 cause SyntaxError. This has been changed to just return which is Py2 and Py3 compatible way how to stop generator.
=> Make generator functions compatible with Py2

ayon_api/server.py
The `204 No Content` response has no text, so it was tripping the `response.json()` invocation for the `patch` calls.
=> Handle RestApiResponse code 204

ayon_api/__init__.py, ayon_api/server.py, ayon_api/server_api.py
Connection can behave as other user if is using service API key which can be also nested using context manager method 'as_user'. Added more options how connection to server can be created. The global API using environment variables can also expect site id and client version.
=> Added support to behave 'as user' and change global con args

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/entity_hub.py, ayon_api/server_api.py
Renamed `ServerAPI` to `GlobalServerAPI` and `ServerAPIBase` to `ServerAPI`. What was base is actually a server api connection with all methods and it's not just a base. And global server api is just using environment for source of authentication.
Final PR of api names refactor.
=> General: Refactor API names p3

ayon_api/_api.py, ayon_api/server_api.py
Fix names of used methods for project root overrides.
Change usage of `get_project_roots` to `get_project_roots_by_site`.
=> Fix: Use right method names

ayon_api/constants.py, ayon_api/server_api.py
Use `files.name` instead of `files.baseName` as field for representations.
=> Representation: Fix constant for files fields

ayon_api/server_api.py
We currently pass fields to the GraphQL query when checking if a project exists on Ayon before attempting to create it, this triggers a GraphQL error if the project doesn't exist, since it can't return the specified field.
=> `server_api.create_project` remove GraphQL fields

ayon_api/server_api.py
Check if arguments passed to rest methods are not empty values. If they are empty values the rest call may change it's purpose.
When `get_project("")` is called it would return all projects instead of `None`.
=> REST arguments validation

ayon_api/entity_hub.py
When we are creating new entities we should add their ID to the processed list so that in case the implementation is wrong, it doesn't attempts to create them twice, which will trigger the unique ID error on the server.
=> `EntityHub` fix not adding new entities to processed list

ayon_api/entity_hub.py
When deleting an entity, the `EntityHub` will try to find its parent,
we weren't fetching the actual Ayon entity but the list of children its
parent has, with this change we now find the actual entity of the parent
and perform the `remove_child` against it.
=> `EntityHub.delete_entity` fix removing entity from parent children

ayon_api/server_api.py
Entity links were always querying only folders so for folders it worked but did not for any other entity type.
I tested the functionality on folders so it worked for me before.
=> Links: Use right GraphQl functions

ayon_api/graphql_queries.py, ayon_api/server_api.py
Method `get_events` is using filtering key `"projectName"` instead of `"projectNames"` for event filtering.
=> GraphQl: Fix events filtering

ayon_api/entity_hub.py
Set created to `False` on lock. New entities have created attribute which stays set to `True` even when entity is locked (all changes are commited). That can cause issues when entity is reused for other purposes after calling commit changes on hub.
=> EntityHub: Unmark 'created' on entity lock

ayon_api/server_api.py
Made fail safe access to `data` attribute on custom response object. Data are set to empty dictionary if fails with json decode error, that reduces checks for status codes which may contain data in some cases and should not contain then in others.
=> Response: Fix data access

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/entity_hub.py, ayon_api/server_api.py
Folder and task type updates can handle renamed type names.
Rename of types could cause crash on server side, because they may be in use on existing entities. Entity hub makes sure the union of old and new folder and task types are pushed first, then are done hierarchy changes and at the end is pushed the final state of folder and task types on project.
=> EntityHub: Sync issues with folder and task types

ayon_api/server_api.py
ServerAPI have option to enable/disable ssl verification and define path to certification file.
Certification file can be passed to `ServerAPI` init, or use env variable `AYON_CERT_FILE`, or standard `SSL_CERT_FILE` env variable.
=> SSL certification: Added option to change certification of ServerAPI

ayon_api/server_api.py
Delete installer (`delete_installer`) is using right endpoint.
=> Desktop: Fix typo in delete installer

ayon_api/server_api.py
Changed upload request type from `POST` to `PUT`.
It looks like it was a bug that was there for a long time. Added option to define different request type if any would need some.
=> Upload request types

ayon_api/_api.py, ayon_api/server_api.py
Initialization of `ServerAPI` will trigger session creation if token is set, so it is not necessary to call `create_session` after object creation.
In most of cases of `ServerAPI` usage we want to create a session. For cases a session is not created on init and token is passed to init there is a trigger to validate the token before a call to server happens.
=> Create session on ServerAPI initialization

ayon_api/server_api.py
The backend allows us to pass filters when enrolling events for a more fine grained query, this commit allows us to specify said filters when enrolling events with this package.
=> `events.enroll` allow passing filters

ayon_api/server_api.py
Make sure the login method does not change `_token_is_valid` when calling `post` to login to server.
The login did raise error about invalid credentials even if credentials are valid because the POST method call set that current token is invalid.
=> Fix login method

README.md, ayon_api/entity_hub.py
Implemented changes of project statuses for entity hub.
Project entity has `statuses` which is object that helps to maintain statuses. It is possible to access existing statuses, modify or remove them, or create new statuses.
```python
from ayon_api.entity_hub import EntityHub
project_name = "<Your project>"
entity_hub = EntityHub(project_name)
project = entity_hub.project_entity
new_status = project.statuses.create("testStatus")
entity_hub.commit_changes()
new_status.set_index(0)
entity_hub.commit_changes()
project.statuses.set([
{
"name": "TheOnlyOne",
"shortName": "NEO",
"color": "#008f11",
"state": "done",
"icon": "eyeglasses"
}
])
entity_hub.commit_changes()
```
=> Entity hub: Project statuses

ayon_api/thumbnails.py
Thumbnail cache is using correct appdirs where to store thumbnails. Changed to `AYON` and `Ynput`.
Remove caching from ayon python api completelly.
=> Use correct appdirs

ayon_api/constants.py, ayon_api/server_api.py
Added support for 0.4.x server.
The only differences are that user `roles` were renamed to `accessGroups` and `dependency_packages` endpoint is now in camel case (`dependencyPackages`).
=> Server 0.4.x support

ayon_api/server_api.py, ayon_api/utils.py
URL validation also use the same timeout value. It did not use any timeout which means it could run infinite amount of time.
Moved default implementation of 'get_default_timeout' to utils which is used by default in `ServerAPI`.
=> Timeout: Use timeout for URL validation

ayon_api/server_api.py
Use `dependencyPackages` endpoint instead of `dependency_packages`. Add warning for deprecated `dependencies` endpoint.
Ednpoint `dependency_packages` is deprecated and will be removed from server soon.
=> Dependency packages endpoint

ayon_api/server_api.py
Added support of `progress` and `retries` on event endpoints. Those were added in server `0.5.x`.
=> Events: progress and retries could be updated on a event

ayon_api/server_api.py
Do not break on connection error and continue in retries. Also log warning with error on last try, to know what exactly happened.
Connection error can happen when a connection is in closing state on server and client send new request.
=> Max retries: Continue in retries on ConnectionError

ayon_api/server_api.py
Make sure graphql query has `active` in fields even if rest should be used.
Resolves https://github.com/ynput/ayon-python-api/issues/101
=> Fix active validation in versions query

ayon_api/server_api.py
Do not validate settings variant which is required for develop mode where variant should be name of bundle to use it properly.
=> Settings variant validation less strict

ayon_api/entity_hub.py
With AYON server version 0.6.x will folder paths start with slash. Entity hub was changed accordingly.
=> Prepare entity hub for folder paths starting with slash

ayon_api/server_api.py
When response object does not have original response and `raise_for_status` an understandable error is raised instead of None type does not have attribute.
=> Handle case when response does not have original respose

ayon_api/_api.py
Public function `get_default_settings_variant` uses correct method `get_default_settings_variant`.
=> Use correct method in public 'get_default_settings_variant'

ayon_api/server_api.py
We'll need to use string for file size of representation because GraphQl supports only 32-bit int.
The size is always converted to `int` > it is not necessary to handle server versions, if it was already int nothing really happens.
=> Expect representation file size as string

ayon_api/server_api.py
Use correct key `productId` instead of `parent` when mapping versions by parent id.
=> Fix get last versions function

ayon_api/server_api.py
Uploading is stream based and transfer progress can be captured. Methods uploading thumbnails are using `upload_file` method now (by allowing **kwargs to method).
=> Upload file updates progress over time

ayon_api/server_api.py
Make sure `productId` is in fields for 'get_last_versions'.
=> Fix get last version fields

ayon_api/entity_hub.py
Property `changes` could return `"data"` with `UNKNOWN_VALUE` which should not happen.
Add custom None for better logging.
=> Entity hub does not send UNKNOWN_VALUE in data

ayon_api/exceptions.py
Make sure all path items from error are strings.
=> GraphQlQueryFailed exception path conversion

ayon_api/entity_hub.py
Dynamically loaded folder entities do not have filled `has_published_content` correctly.
All dynamically loaded folders had `has_published_content` set to `False` even they had published assets which lead to misleading information for automations.
=> Entity Hub: Dynamically loaded entities have filled 'has_published_content'

ayon_api/server_api.py
Use `raise_for_status` for validation of event dispatch method. Output of the method is not boolean anymore.
Implemented proper `__bool__` method for `RestApiResponse` and ouput of `__len__` is `int`.
This change may be backwards incompatible change as the previous behavior returned boolean and just logged out the information -> We should probably go through the known usages and revalidate the change.
=> Dispatch event raises when fails

ayon_api/_api.py
Function `get_service_addon_settings` does support `project_name` argument.
=> Service setting can be received for a project

ayon_api/server_api.py
Function `get_last_version_by_product_name` used invalid field `"_id"` to get product.
=> Fix fields in `get_last_version_by_product_name` 

ayon_api/server_api.py
Function `get_project_anatomy_preset` should use primary anatomy preset when preset name is not defined, but it did use built-in all the time. To get primary preset name was implemented `get_default_anatomy_preset_name`.
=> Use primary anatomy preset instead of builtin

ayon_api/server_api.py
AYON server 1.0.8 added support for `__primary__` and `__builtin__` preset placeholders to easier get the coresponding value. The values can be used with the api.
=> Preset name: Use primary and builtin preset name placeholders

ayon_api/constants.py, ayon_api/server_api.py
Project can fetch `folderTypes`, `taskTypes` and `productTypes` fields easily.
Resolves https://github.com/ynput/ayon-python-api/issues/137
=> Easier nested fields on project

ayon_api/server_api.py
Auto expand `"files"` field on representation to it's nested fields.
=> Easier nested fields on representation

ayon_api/entity_hub.py
Using `get_or_query_entity_by_id` does not use tasks fields defined by entity hub which causes error when creating `TaskEntity` from data.
=> Entity hub: Use task fields to fetch tasks

ayon_api/constants.py, ayon_api/entity_hub.py
All entities do support `"status"` and `"tags"` in fields, which are now fetched by default.
=> Chore: Added 'status' and 'tags' to default fields

ayon_api/_api.py, ayon_api/graphql_queries.py, ayon_api/server_api.py, ayon_api/utils.py
It is possible to fetch task entity with representation hierarchy.
The task entity is connected to version entity. Value of `task` is `None` If `"taskId"` is not set on version.
=> Repre Hierarchy: Fetch also task entity

ayon_api/server_api.py
Use empty dictionary when `"data"` value is `None`.
When data are empty on entity server does return `None` instead of `"{}"`, added functionality makes `None` value as dictionary.
=> Data contains dictionary if value is empty

ayon_api/_api.py, ayon_api/graphql_queries.py, ayon_api/server_api.py
Added new filtering options, replace some existing and added helper functions to reduce code.
- Added event ids filter to `get_events`.
- Added task ids filter to `get_versions`.
- Dispatched event can define `"dependOn"` id.
- Added assignees filtering for folders.
- Better docstring for `standard` and `hero` argumets in `get_versions`.
- Update version supports to change `author`.
- Added helper functions for preparation of filters.
1. Validate code changes.
2. Functions work as expected.
3. Docstrings make sense.
=> Chore: Small API update

ayon_api/server_api.py
Convert representation in `get_representations_hierarchy`.
1. Returned representations from `get_representations_hierarchy` have `"data"` as dictionary.
Resolves https://github.com/ynput/ayon-python-api/issues/178
=> Representation hierarchy: Convert representation data

ayon_api/server_api.py
Field `"data"` in workfile info entity is converted to dictionary.
The `"data"` on entities are returned as json string from AYON server. For other entities it is already converted, workfile info was missing.
1. Each entity received using `get_workfiles_info` or `get_workfile_info` should have `"data"` as dictionary.
Resolves https://github.com/ynput/ayon-python-api/issues/187
=> Workfiles info: Convert workfile info data to dictionary

automated_api.py, ayon_api/_api.py
Do not copy 'get_default_settings_variant' on auto api creation.
The function has custom implementation in `_api.py`.
1. Running `automated_api.py` script should not cause any changes in `_api.py`.
=> Chore: Automated api does not copy 'get_default_settings_variant'

ayon_api/utils.py
Use correct endpoint to abord action.
=> WebAction: Use abort endpoint instead of take

automated_api.py, ayon_api/_api.py
Modified automated api script to fill in all arguments with same defaults as are used in `ServerAPI` to `_api.py` functions.
Also added typehints logic, but that is not 100%, should not break the code if "fails" to resolve the typehint correctly.
1. IDEs should start to supply arguments available on public functions.
2. Import of `ayon_api` does not cause any issues and works as before.
=> Chore: Public api does automatically fill in all arguments with typehints

ayon_api/server_api.py
Function `get_representations_hierarchy` does convert fields the same way as other getter functions.
Implemented helper function to convert fields for each entity type which is used across all functions.
1. Call `get_representations_hierarchy` (or `get_representation_hierarchy`) with e.g. folder fields containing `"attrib"`.
2. You should get all attributes of the entity.
Resolves https://github.com/ynput/ayon-python-api/issues/212
=> Representations hierarchy: Handle fields same way as in other functions

ayon_api/server_api.py
As username stack now reverts to previous user correctly.
As username functionality did not set the username to previouse username when context manager ended.
1. When using `as_username` stack on `ServerAPI` object it does return to previous user when ended.
=> Chore: As username stack works

ayon_api/server_api.py
It is possible to run `as_username` contextmanager and ignore error if used api key is not a service api key.
Sometimes the functionality to work as other user is not mandatory and can be done even if is not running as service user. Maintining that in code is hard because to work as other user a context manager must be used which complicates the code below it a lot.
1. It is possible to use `with api.as_username("someuser", ignore_service_error=True)` event if API key is not service API key.
=> As username functionality can ignore service user error

ayon_api/server_api.py
Returns the task id when creating the task instead of the folder id
changed the return from folder id to task id 
Resolves https://github.com/ynput/ayon-python-api/issues/214
=> Return task id when creating a task using the create task function

ayon_api/_api.py, ayon_api/graphql_queries.py, ayon_api/server_api.py
Use `statuses` instead of `states` for events filtering.
The `statuses` fitler is available in current develop (first release after 1.5.6) where `states` becomes deprecated filter and should not be used anymore.
Use `statuses` as default argument in `get_events`, but still support `states` with deprecation warning.
1. Use `statuses` in `get_events`.
2. It should automatically use `states` or `statuses` GraphQl filter based on server version.
=> Events: Use statuses for events filtering

ayon_api/server_api.py
Add detail to error message if is available and fill content if is not available.
Currently the error on failed operations does not tell anything usefull when happens. Also added `ok` property to response class, it was not needed at the end in this PR, but I already had it there...
1. Failed operations should tell why it crashed.
=> Operations: Better error message

poetry.lock, pyproject.toml
Removed unused `appdirs` dependency.
Not sure if it was ever used, but is not used in the codebase at this moment.
1. Validate that appdirs is really not used.
=> Chore: Removed appdirs from dependencies

ayon_api/server_api.py
Function `get_projects` does respect `active` filtering.
The `active` argument was ignored when project were fetched using GraphQl.
1. Make sure you have at least on active and one inactive project in AYON.
2. Run the `get_projects` with different `active` filtering options. `True` only active projects, `False` only inactive, `None` all projects.
Resolves https://github.com/ynput/ayon-python-api/issues/238
=> Projects query: Fix active filtering

ayon_api/entity_hub.py, ayon_api/server_api.py
Removed really outdated backwards compatibility handling from codebase.
With changes made in this PR can be ayon python api use with any server backend `>=1.0.0`.
1. Validate changes made.
=> Chore: Remove backwards compatibility

ayon_api/server_api.py
Header `referer` can be used by server to fill in "client's server url".
That is helpfull for e.g. webactions which need to pass correct server url into the triggered process.
Nothing much to validate.
=> Headers: Pass in 'referer' header

ayon_api/utils.py
Validate url does handle scheme update (`http` -> `https`), and uses same verify and cert values as `ServerAPI` does.
Not sure how to test cert and verify? If `validate_url` is used on ssl secured address, the output url should be always `https`.
1. Pass `http://some.secure.ayon` into the function.
2. Output should be `https://some.secure.ayon`.
=> Utils: Validate url enhancements

ayon_api/server_api.py, ayon_api/utils.py
Machine name passed to headers is unidecoded as unicode characters can't be used for header value.
1. Chance machine name to contain unicode characters not available in ASCII (`ěščřžýáíé`).
2. Try to create connection using ayon api.
3. It should not fail.
Resolves https://github.com/ynput/ayon-python-api/issues/230
=> Chore: Uunidecode machine name for header value

ayon_api/server_api.py
Convert parse json string values and convert ownAttrib on user to same structure as on other entities.
1. Function `get_users` does not require `accessGroups` in `fields` if are customized.
2. Values of `accessGroups` and `allAttrib` are converted from json string to python object when received using `get_users`.
3. Function `get_user` does fill `ownAttrib` the same way as other entities (making it a dictionary with `None` values for those which don't have own values on user).
=> User: Data conversion

ayon_api/_api.py, ayon_api/constants.py, ayon_api/graphql_queries.py, ayon_api/server_api.py
Functions `get_project` and `get_projects` now do support to get 'productTypes' with other fields.
If `productTypes` are requested in fields then API uses GraphQl to get list of projects instead of projects endpoint.
Because data from graphql and REST are not 1:1 matching it was necessary to implement some conversion of the data to keep unified structure (e.g. 'bundle').
1. Function `get_project_product_types` still works and returns product types used on project.
2. Using `get_project` and `get_projects` with `{"productTypes"}` in fields does return the projects with productTypes.
=> Project fetching updates

ayon_api/_api_helpers/workfiles.py, ayon_api/graphql_queries.py
Fix typo `workfilehasLinks` to `workfileHasLinks`.
1. Validate code changes
=> GraphQl: Fix typo in workfiles filter variable name

pyproject.toml, setup.py
Change project name to `ayon_python_api` which is sanitized name according to PEP 625.
This should fix issue related to PEP 625.
Validation of this will happen on next release.
=> Chore: Change project name to 'ayon_python_api'
