ynput/ayon-python-api

ayon_api/__init__.py, ayon_api/server.py, ayon_api/server_api.py
Implemented methods to get/update and dispatch events. Also implemented "enroll event" to create event jobs based on event topic.
=> Events: Basic support for events

ayon_api/server.py, ayon_api/utils.py
Use more universal attribute and method names in `TransferProgress` class to suit both download and upload.
=> TransferProgress: Better attribute and method names

ayon_api/server.py
Generator functions returned empty list which is invalid which in Py3 it silently continue but in Py2 cause SyntaxError. This has been changed to just return which is Py2 and Py3 compatible way how to stop generator.
=> Make generator functions compatible with Py2

pyproject.toml, setup.py
Added missing dependencies to setup.py and fix `unidecode` to `Unidecode` in pyproject toml.
=> Add missing dependencies

ayon_api/server.py, pyproject.toml, setup.py
Fix support for Python 2. Lowered unidecode to 1.2.0 and skip usage of `HTTPStatus` if is not available.
=> General: Fix Python 2 support

ayon_api/__init__.py, ayon_api/constants.py, ayon_api/graphql_queries.py, ayon_api/server.py, ayon_api/server_api.py
Added function `get_events` to get multiple events using graphql with possible filters.
=> Events: Query events using graphql

README.md
Updated readme. Removed already done TODOs.
=> General: Update readme

ayon_api/__init__.py, ayon_api/server_api.py
Added more helper functions for services to avoid direct access to environments as much as possible.
=> Services: More helper functions for service

ayon_api/utils.py
Add missing argument to formatting of error message.
=> General: Fix formatting error

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
Implemented function to receive representation ids by context filters.
=> Representation context filters

ayon_api/entity_hub.py
Fix issue of project entity id which seems to create random uuid string instead of using project name as id. At the same time new created folder without defined parent is automatically child of project.
=> Entity hub: Folder creation fix

README.md, ayon_api/server_api.py
Filled few docstrings in server_api.py and updated README.md.
=> Docs: Update/fill docstrings and update readme

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
Added helper function to calculate addon url.
=> General: Addon url calculation

ayon_api/exceptions.py, ayon_api/server_api.py
Added custom exception for invalid http request by status which is raised when `raise_for_status`. Also changed how repr or response look like.
=> General: Custom REST exception

ayon_api/__init__.py, ayon_api/_api.py
Function `get_project_names` is added to public api.
=> API: Added 'get_project_names' to api functions

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
Server version 0.2.1 introduced new concept of deployment and version control of addons which changed how dependency pacakges are created/updated. Implemented new functions for desktop application. To maintain desktop application installers, dependency packages and wrapping mechanism called "bundle".
The modifications should be backwards compatible with older servers but desktop application must handle versioning too.
=> Feature: Desktop endpoints

ayon_api/__init__.py, ayon_api/_api.py
Added `get_folders_hierarchy` function to public api functions.
=> Function 'get_folders_hierarchy' is in public api functions

ayon_api/server_api.py
Fix key used in `create_installer` to define algorithm type.
=> Installer: Fix 'checksumType' to 'checksumAlgorithm'

ayon_api/server_api.py
Added new information about runtime python modules to installer metadata.
=> Installer: Added runtime modules

ayon_api/utils.py
Fixed used variable `done` to `transfer_done` and removed duplicated attribute definition `content_size`. Fixed typo in `transfered` to `transferred` and adde some dosctrings.
=> Transfer progress: Fix used variables

ayon_api/server_api.py
Implemented `get_folders_hierarchy` which is in public api but is not implemented in `ServerAPI`.
=> Folder hiearchy: Implement missing folder hierarchy method

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
Implemented endpoint to upload addon zip. New method `upload_addon_zip`.
=> Addons: Upload addon zip

ayon_api/_api.py
Stop using deprecated environment variables with `AY_` prefix in services.
=> Service: Removed usage of deprecated environment variables

ayon_api/server_api.py
Support older `requests` module without `JSONDecodeError` in exceptions.
=> Older requests support

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
Added endpoints to work with secrets.
=> Secrets: Functions for secret endpoints

ayon_api/__init__.py, ayon_api/_api.py
Aadded `get_task_by_id` and `get_task_by_name` to public functions.
=> Missing public functions

ayon_api/constants.py, ayon_api/graphql_queries.py, ayon_api/server_api.py
Function `get_users` actually returns users instead of `None`.
Use `get_users` which should be iterable of users.
=> Users: Working method 'get_users'

ayon_api/__init__.py, ayon_api/_api.py, ayon_api/server_api.py
It is possible to get all attribute fields for an entity type by passing `"attrib"` to `fields`. Fixed few typos in `fields`. Added more entity types to `get_default_fields_for_entity_type`.
=> Fields enhancements

ayon_api/operations.py
Updated create new entities data functions, to be up to date with current rest api options.
=> Operations: Functions update

ayon_api/graphql_queries.py, ayon_api/server_api.py
Added option to filter products by product type and statuses. Fixed attrib files receivement for products.
=> Products: More filtering

ayon_api/graphql_queries.py, ayon_api/server_api.py
Added option to filter folders by folder type and status.
=> Folders: More filtering options

ayon_api/server_api.py
Fixed example output data of `get_entities_links`.
=> Docstring: Fix 'get_entities_links' docstring

ayon_api/_api.py
Use correct methods in public actions to get and save secret value.
=> Fix secrets public function

ayon_api/utils.py
Add timeout to all utils functions.
=> Utils: Use timeout in all functions

ayon_api/utils.py
Function `is_token_valid` also validates if token is service api key.
=> Validate token can work with service api key

ayon_api/_api.py, ayon_api/graphql_queries.py
Some public functions did not return output of called ServerAPI method.
=> Public functions return value

ayon_api/server_api.py
Fill `"maxRetries"` only if the value is filled.
=> Fix 'enroll_event' queries

ayon_api/constants.py, ayon_api/entity_hub.py, ayon_api/server_api.py
AYON server does support to query 'data' field for hierarchy entities (project > ... > representation) using GraphQl since version 0.5.5. Ayon api can not use that option too.
=> Query 'data' using GraphQl

ayon_api/server_api.py
Make sure hero versions are not returned when looking for latest version.
=> Last versions: Make sure hero version are not handled in last versions

ayon_api/operations.py, ayon_api/server_api.py, ayon_api/utils.py
Added entity type specific methods for better api.
=> Operations session: Added entity type specific methods

ayon_api/entity_hub.py
Create body did not set label of an entity which caused issues.
=> EntityHub: Add label to create body

ayon_api/entity_hub.py
Lock of folder and task entity will reset original label for future commit changes.
=> EntityHub: Lock label on folder and task entity

ayon_api/entity_hub.py
Add support to set task assignees through Entity Hub
=> Add support to set task assignees through Entity Hub

README.md, ayon_api/entity_hub.py, ayon_api/graphql.py, ayon_api/operations.py, ayon_api/server_api.py, ayon_api/utils.py, poetry.lock, pyproject.toml, setup.py
=> Chore: Drop Python 2 support

ayon_api/entity_hub.py, tests/test_entity_hub.py
Fix implementation of `from_entity_data` on `ProjectEntity` and use the method. 
Added tests for changing status on entities.
=> Entity hub: Project entity initialization

ayon_api/server_api.py
Log that server is occupied on 503 status in enroll event.
=> Enroll event: Log info message when server is occupied

ayon_api/__init__.py, ayon_api/utils.py
Added helper function to get user with token.
Extracted functionality from `is_token_valid` to be able to use it directly.
Check code changes.
=> Chore: Added get user function

docs/source/index.rst
Just a fix of the link to the github repository :)
=> Fix link to github repository

ayon_api/server_api.py
It is possible to get thumbnail for task easily.
Entity type `"task"` was not listed in available entity types to auto-correct `"s"` in the endpoint.
1. Validate made changes.
=> Thumbnails endpoint: Added task to allowed entity types

ayon_api/utils.py
Remove accidentally added line causing it still work as before.
=> Chore: Unidecode machine name for header value pt.2

ayon_api/operations.py, ayon_api/server_api.py
Fix deletion of representation entities.
Fix url used to delete representation, and fix typo in operations.
1. Representations can be deleted.
=> Delete representation fix
